config/routes.rb
Rails.application.routes.draw do
=begin
  get 'orders/add/:id', to: 'orders#add', as:'orders_add'
  get 'orders/show'
  get 'orders/index'
  get 'purchases/add/:id', to: 'purchases#add', as:'purchases_add'
  get 'purchases', to: 'purchases#index', as:'purchases_index'
  post 'purchases/add', to:'purchases#add_to_cart', as:'orders'
  get 'purchases/:id', to: 'purchases#show', as: 'purchase'
  get 'purchases/:id/edit', to: 'purchases#edit', as: 'purchase_edit'
  patch 'purchases/:id', to: 'purchases#update', as: 'purchase_update'
  get 'purchases/:id/submit', to:'purchases#submit', as:'purchase_submit'
  get 'purchases/:id/close', to:'purchases#close', as:'purchase_close'
  get 'purchases/:id/cancel', to:'purchases#cancel', as:'purchase_cancel'
  get 'purchases/:id/delete', to:'purchases#delete', as:'purchase_delete'
=end
    
  devise_for :users

  resources :items
  resources :orders, only: [ :show, :index]
  resources :orders, path: "orders/:id/", only: [ :new ]
  resources :purchases, except: [ :new ] do
    member do
      get :submit
      get :close
      get :cancel
      get :reject
    end  
  end 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
	has_many :orders
	has_many :purchases, through: :orders

	validates :name, presence: true
	validates :description, presence: true
	validates :images, presence: true
	validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :item
	belongs_to :purchase

	validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :totalPrice, presence: true, numericality: {greater_than_or_equal_to: 1}
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	belongs_to :user
	has_many :orders
	has_many :items, through: :orders
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :assignments
	has_many :users, through: :assignments

end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	has_many :orders
	has_many :items, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :purchases
	has_many :assignments
	has_many :roles, through: :assignments

  def role?(role)  
	roles.any? { |r| r.name.underscore.to_sym == role }  
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit


  	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private

  	def user_not_authorized(exception)
    	redirect_to root_path
  	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new()
    authorize @item
  end

  # GET /items/1/edit
  def edit
    authorize @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    authorize @item
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :stock, :price, :images, :category_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:new]

  def new

  end

  def index
    @orders = current_user.purchases.where(status:'open')[0].orders
  end   

  def show
    
  end

  private

    def set_order
      @item = Item.find(params[:id])
      @order = Order.new()
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, only: [:show, :submit, :cancel, :close, :destroy, :edit, :reject]
  before_action :set_open_purchase, only: [:create]

  def create
  	if (@order = @purchase.orders.where(item_id: order_params[:item_id]).any?)
		  redirect_to action: "edit", id: @purchase.id
    else
      @purchase.orders.create(item_id: order_params[:item_id], quantity: order_params[:quantity], purchase_id: @purchase.id,
      totalPrice: (order_params[:quantity].to_i * (Item.find(order_params[:item_id]).price.to_f)))
      redirect_to action: "show", id: @purchase.id
    end
    #redirect_to action: "edit", id: @purchase.id
  end

  def update
    @purchase = Purchase.find(params[:id])
    i=0    
    @purchase.orders.each do |order|
      order.update(quantity: purchase_params[:quantity][i],
        totalPrice: purchase_params[:quantity][i].to_i *
        Item.find(order.item_id).price.to_f)
      i =+ 1
    end
    @purchase.update(:orders => @purchase.orders)
    respond_to do |format|
      format.html { redirect_to @purchase, notice: 'Purchase was successfully edited.' }
      format.json { render :show, status: :ok, location: @purchase }
    end
  end

  def edit
  end

  def index
    @purchases = current_user.purchases
    if current_user.role? :admin
      @purchases = index_all
    end
  end

  def show
  end

  def destroy
    Purchase.find(@purchase.id).delete
    redirect_to action: "index"
  end

  def submit
    @purchase.status = 'pending'
    @purchase.save
    redirect_to action: "show", id: @purchase.id
  end

  def cancel
    @purchase.status = 'cancelled'
    @purchase.save
    redirect_to action: "show", id: @purchase.id
  end

  def reject
    @purchase.status = 'rejected'
    @purchase.save
    redirect_to action: "show", id: @purchase.id
  end

  def close
    @purchase.status = 'completed'
    @purchase.save
    redirect_to action: "show", id: @purchase.id
  end

  private

    def index_all
      @purchases = Purchase.all
    end  

    def set_open_purchase
     	@purchase = Purchase.where(user_id: current_user.id, status: 'open')[0]
      if(@purchase==nil)
        @purchase = Purchase.create(user_id: current_user.id, status: 'open')
      end
    end

    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:quantity => [])
    end

    def order_params
      params.permit(:item_id,:quantity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/applications/_current_user.html.erb
<% if user_signed_in? %>
	Welcome <%= current_user.email %>.
	<%= link_to "Sign out", destroy_user_session_path, data: { method: :delete } %>
	<%= link_to "Purchases", purchases_path	 %>
<% elsif !devise_controller? %>
	<%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Price</th>
      <th>Images</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.stock %></td>
        <td><%= item.price %></td>
        <td><%= item.images %></td>
        <td><%= Category.find(item.category_id).name %></td>
        <td><%= link_to 'Show', item %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Add to cart', new_order_path(item) %></td>
          <% if current_user.role? :admin %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? and current_user.role? :admin %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/index0.html.erb
<%= javascript_pack_tag 'index' %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @item.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Images:</strong>
  <%= @item.images %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@item.category_id).name %>
</p>

<% if user_signed_in? and current_user.role? :admin %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>

<% if user_signed_in? %>
  <td><%= link_to 'Add to cart', orders_add_path(@item) %></td>
<% end %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClothesShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'applications/current_user'%>
    <%= yield %>
  </body>
</html>

app/views/orders/_add-form.html.erb
<%= form_with(model: @order) do |form| %>
  
  <%= form.hidden_field :item_id, :value => @item.id %>

  <p>
    <strong>Name:</strong>
    <%= @item.name %>
  </p>

  <p>
  <strong>Description:</strong>
    <%= @item.description %>
  </p>

  <p>
  <strong>Price:</strong>
    <%= @item.price %>
  </p>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', items_path %>

app/views/orders/_new-form.html.erb
<%= form_with(url: '/purchases', local:true) do |form| %>
  
  <%= form.hidden_field :item_id, :value => @item.id %>

  <p>
    <strong>Name:</strong>
    <%= @item.name %>
  </p>

  <p>
  <strong>Description:</strong>
    <%= @item.description %>
  </p>

  <p>
  <strong>Price:</strong>
    <%= @item.price %>
  </p>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', items_path %>

app/views/orders/index.html.erb
<h1>Order#index</h1>
<p>Find me in app/views/order/index.html.erb</p>

app/views/orders/new.html.erb
<%= render 'new-form', locals: { item: @item, order: @order} %>

app/views/orders/show.html.erb
<h1>Order#show</h1>
<p>Find me in app/views/order/show.html.erb</p>

app/views/purchases/edit.html.erb
<%= form_with(model: @purchase, local: true) do |form| %>

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>ID:</strong>
	  <%= @purchase.id %>
	</p>

	<p>
	  <strong>Status:</strong>
	  <%= @purchase.status %>
	</p>

	<p>
	  <strong>Last update:</strong>
	  <%= @purchase.updated_at %>
	</p>

		<table>
		  <thead>
		    <tr>
		      <th>Item name</th>
		      <th>Quantity</th>
		      <th>Price</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @purchase.orders.each do |order| %>
		      <tr>
		        <td><%= order.item.name %></td>
		        <td>
		        	<div class="field">
			      		<%= form.number_field :quantity, multiple: true, value: order.quantity %>
			    	</div>	
			    </td>
		        <td><%= order.totalPrice %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

	<div class="actions">
		<%= form.submit %>
	</div>

	<br>

	<%= link_to 'Back', purchase_path(@purchase) %>
<% end %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Purchase Id</th>
      <% if current_user.role? :admin %>
        <th> User </th>
      <% end %>  
      <th>Status</th>
      <th> Last update </th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.id %></td>
        <% if current_user.role? :admin %>
          <td><%= purchase.user.email %></td>
        <% end %>
        <td><%= purchase.status %></td>
        <td><%= purchase.updated_at %></td>
        <td><%= purchase.orders.inject(0){|sum,x| sum + x.totalPrice }%></td>
        <td><%= link_to 'Show', purchase_path(purchase) %></td>
        <% if current_user.role? :admin %>
          <td><%= link_to 'Delete', purchase_path(purchase), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', items_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @purchase.id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @purchase.status %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @purchase.updated_at %>
</p>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase.orders.each do |order| %>
      <tr>
        <td><%= order.item.name %></td>
        <td><%= order.quantity %></td>
        <td><%= order.totalPrice.to_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user == @purchase.user and @purchase.status == 'open' %>
  <%= link_to 'Edit purchase', edit_purchase_path(@purchase) %>
  <%= link_to 'Submit purchase', submit_purchase_path(@purchase) %>
  <%= link_to 'Cancel purchase', cancel_purchase_path(@purchase) %>
<% end %>
<% if current_user.role? :admin and @purchase.status == 'pending'%>
  <%= link_to 'Approve purchase', close_purchase_path(@purchase) %>
  <%= link_to 'Reject purchase', reject_purchase_path(@purchase) %>
<% end %>
<%= link_to 'Back', purchases_path %>